apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - ransom-rampage
  selector:
    matchLabels:
      argocd.argoproj.io/instance: api-gateway
  endpoints:
    - targetPort: 8000
      path: /metrics
      interval: 15s
