apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: ransom-rampage
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-cognito: >
      {
        "userPoolARN": "arn:aws:cognito-idp:eu-west-1:810729346256:userpool/eu-west-1_Ixvrmycm5",
        "userPoolClientID": "2h873rm9o50b0fh1cu40nqe1es",
        "userPoolDomain": "ransomrampage"
      }
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:810729346256:certificate/758f6356-747d-447e-8cf6-04da6e0bec11"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
spec:
  rules:
  - host: argocd.ransomrampage.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
