import pytest
import copy

from dotenv import load_dotenv

load_dotenv()  # Charge .env pour OPENAI_API_KEY

# ============================================================
# Canonical fake_state for all tests (from notebook cell 14)
# ============================================================

FAKE_STATE = {
    "company": {
        "name": "NeoVenture",
        "description": "A disruptive neobank for gig workers",
        "sector": "neobank",
        "adversary": "mafia",
        "cash": 4500,
        "turn": 3,
        "compliance": 0.65,
        "reputation": 0.75,
        "insurance_active": False,
        "insurance_premium": 0,
        "breach_reported": False,
    },
    "nodes": [
        {
            "id": "n1",
            "name": "API Gateway",
            "type": "entry",
            "throughput": 7,
            "defense": 3,
            "visibility": 8,
            "cost": 4,
            "compliance_score": 6,
            "compromised": False,
            "locked": False,
            "offline": False,
            "isolated": False,
            "fogged": False,
            "has_mfa": False,
            "monitored": False,
            "offline_turns": 0,
        },
        {
            "id": "n2",
            "name": "Auth Service",
            "type": "middleware",
            "throughput": 6,
            "defense": 5,
            "visibility": 6,
            "cost": 3,
            "compliance_score": 7,
            "compromised": False,
            "locked": False,
            "offline": False,
            "isolated": False,
            "fogged": True,
            "has_mfa": False,
            "monitored": False,
            "offline_turns": 0,
        },
        {
            "id": "n3",
            "name": "Payment Engine",
            "type": "server",
            "throughput": 8,
            "defense": 7,
            "visibility": 5,
            "cost": 6,
            "compliance_score": 8,
            "compromised": False,
            "locked": False,
            "offline": False,
            "isolated": False,
            "fogged": False,
            "has_mfa": False,
            "monitored": False,
            "offline_turns": 0,
        },
        {
            "id": "n4",
            "name": "Core DB",
            "type": "database",
            "throughput": 9,
            "defense": 8,
            "visibility": 4,
            "cost": 7,
            "compliance_score": 9,
            "compromised": False,
            "locked": False,
            "offline": False,
            "isolated": False,
            "fogged": True,
            "has_mfa": False,
            "monitored": False,
            "offline_turns": 0,
        },
        {
            "id": "n5",
            "name": "HR Portal",
            "type": "human",
            "throughput": 3,
            "defense": 2,
            "visibility": 7,
            "cost": 2,
            "compliance_score": 4,
            "compromised": True,
            "locked": False,
            "offline": False,
            "isolated": False,
            "fogged": False,
            "has_mfa": False,
            "monitored": False,
            "offline_turns": 0,
        },
        {
            "id": "n6",
            "name": "Vendor KYC",
            "type": "vendor",
            "throughput": 5,
            "defense": 4,
            "visibility": 3,
            "cost": 5,
            "compliance_score": 5,
            "compromised": False,
            "locked": False,
            "offline": False,
            "isolated": False,
            "fogged": True,
            "has_mfa": False,
            "monitored": False,
            "offline_turns": 0,
        },
        {
            "id": "n7",
            "name": "Analytics Engine",
            "type": "server",
            "throughput": 6,
            "defense": 6,
            "visibility": 6,
            "cost": 3,
            "compliance_score": 6,
            "compromised": False,
            "locked": False,
            "offline": True,
            "isolated": False,
            "fogged": False,
            "has_mfa": False,
            "monitored": False,
            "offline_turns": 1,
        },
    ],
    "edges": [
        {"from": "n1", "to": "n2"},
        {"from": "n2", "to": "n3"},
        {"from": "n3", "to": "n4"},
        {"from": "n1", "to": "n5"},
        {"from": "n5", "to": "n2"},
        {"from": "n4", "to": "n6"},
        {"from": "n3", "to": "n7"},
        {"from": "n4", "to": "n7"},
    ],
    "flows": [
        {
            "name": "Card Payments",
            "node_path": ["n1", "n2", "n3", "n4"],
            "base_revenue": 45,
            "is_active": True,
            "current_revenue": 27,
        },
        {
            "name": "P2P Transfers",
            "node_path": ["n1", "n3", "n4"],
            "base_revenue": 30,
            "is_active": True,
            "current_revenue": 21,
        },
        {
            "name": "KYC Onboarding",
            "node_path": ["n1", "n2", "n6"],
            "base_revenue": 15,
            "is_active": True,
            "current_revenue": 7,
        },
        {
            "name": "Analytics Reports",
            "node_path": ["n3", "n7"],
            "base_revenue": 10,
            "is_active": False,
            "current_revenue": 0,
        },
    ],
    "vulnerabilities": [
        {"node_id": "n1", "severity": 2, "known_by_player": True},
        {"node_id": "n2", "severity": 1, "known_by_player": False},
        {"node_id": "n6", "severity": 3, "known_by_player": False},
    ],
    "byte": {"byte_presence": {"n5": "compromised"}, "byte_ap": 2, "byte_active_ops": []},
    "regulator": {"breach_timer": None, "deletion_requested": False},
    "effects": [],
    "turn_log": [],
}

@pytest.fixture
def fake_state():
    """Deep copy of canonical GDD-compliant state. 7 nodes, 4 flows, 3 vulns, n5 compromised."""
    return copy.deepcopy(FAKE_STATE)