apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acourreg/ransom-rampage.git
    targetRevision: main
    path: helm/microservice
    helm:
      valueFiles:
        - values.yml
      parameters:
        - name: image.repository
          value: 810729346256.dkr.ecr.eu-west-1.amazonaws.com/api-gateway
        - name: image.tag
          # MANAGED_BY_CI
          value: 1216798a41a30ee062fa35582bcba72c25f68031
        - name: service.port
          value: "8000"
        - name: probes.path
          value: /health
        - name: probes.port
          value: "8000"
  destination:
    server: https://kubernetes.default.svc
    namespace: ransom-rampage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acourreg/ransom-rampage.git
    targetRevision: main
    path: helm/microservice
    helm:
      valueFiles:
        - values.yml
      parameters:
        - name: image.repository
          value: 810729346256.dkr.ecr.eu-west-1.amazonaws.com/dashboard
        - name: image.tag
          # MANAGED_BY_CI
          value: 1216798a41a30ee062fa35582bcba72c25f68031
        - name: service.port
          value: "80"
        - name: probes.path
          value: /
        - name: probes.port
          value: "80"
  destination:
    server: https://kubernetes.default.svc
    namespace: ransom-rampage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
