apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acourreg/ransom-rampage.git
    targetRevision: main
    path: helm/microservice
    helm:
      valueFiles:
        - values.yml
      parameters:
        - name: image.tag
          value: 095900b0e5f4f700832bb49d233b12bc4e19bdcc
  destination:
    server: https://kubernetes.default.svc
    namespace: ransom-rampage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acourreg/ransom-rampage.git
    targetRevision: main
    path: helm/microservice
    helm:
      valueFiles:
        - values.yml
      parameters:
        - name: image.tag
          value: 095900b0e5f4f700832bb49d233b12bc4e19bdcc
        - name: service.port
          value: 095900b0e5f4f700832bb49d233b12bc4e19bdcc
        - name: containerPort
          value: 095900b0e5f4f700832bb49d233b12bc4e19bdcc
  destination:
    server: https://kubernetes.default.svc
    namespace: ransom-rampage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
